import React from 'react';
import './globals.scss';
import { Roboto } from 'next/font/google';
import ProviderRedux from '../redux/ProviderRedux';
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};
const roboto = Roboto({
  weight: ['400', '500', '700'],
  subsets: ['latin'],
  style: ['italic', 'normal'],
  display: 'swap',
});
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html className={roboto.className} lang='en'>
      <body className='px-8'>
        <ProviderRedux>{children}</ProviderRedux>
      </body>
    </html>
  );
}
