import HeaderSign from '@/components/common/HeaderSign';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <section>
      <header className="flex justify-between">
        <HeaderSign />
      </header>
      <div>{children}</div>
    </section>
  );
}
